apiVersion: apps/v1
kind: Deployment
metadata:
  name: uberclone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uberclone
  template:
    metadata:
      labels:
        app: uberclone
    spec:
      containers:
      - name: uberclone
        image: ratanpandey07/uberclone:latest
        ports:
        - containerPort: 3000

