apiVersion: apps/v1
kind: Deployment
metadata:
  name: uberclone-app
  labels:
    app: uberclone-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uberclone-app
  template:
    metadata:
      labels:
        app: uberclone-app
    spec:
      containers:
      - name: uberclone-app
        image: ratanpandey07/uberclone:latest
        ports:
        - containerPort: 3000
