apiVersion: v1
kind: Service
metadata:
  name: uberclone-service
  labels:
    app: uberclone
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: uberclone

