apiVersion: v1
kind: Service
metadata:
  name: uberclone-service
  labels:
    app: uberclone-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    app: uberclone-app


